package com.nexus.auth.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;

/**
 * Represents an authenticated user in the system.
 * This entity is stored in the "auth_users" MongoDB collection and is used
 * to track unique client identities across API requests.
 *
 * <p>No password is required; authentication is based solely on user IDs.
 * Each user ID uniquely identifies a client for request differentiation.</p>
 */
@Document(collection = "auth_users")
public class AuthUser {

    /**
     * Unique identifier for the user, auto-generated by MongoDB.
     */
    @Id
    private String id;

    /**
     * Unique user ID used for API authentication.
     * This field is indexed for fast lookups.
     */
    @Indexed(unique = true)
    private String userId;

    /**
     * Timestamp when the user was created.
     */
    private Instant createdAt;

    /**
     * Timestamp of the user's last API access.
     */
    private Instant lastAccessedAt;

    /**
     * Default constructor required for MongoDB deserialization.
     */
    public AuthUser() {
    }

    /**
     * Constructs an AuthUser with the specified user ID.
     *
     * @param userId the unique user identifier for authentication
     */
    public AuthUser(final String userId) {
        this.userId = userId;
        this.createdAt = Instant.now();
        this.lastAccessedAt = Instant.now();
    }

    /**
     * Gets the MongoDB document ID.
     *
     * @return the document ID
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the MongoDB document ID.
     *
     * @param id the document ID to set
     */
    public void setId(final String id) {
        this.id = id;
    }

    /**
     * Gets the unique user ID used for authentication.
     *
     * @return the user ID
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the unique user ID.
     *
     * @param userId the user ID to set
     */
    public void setUserId(final String userId) {
        this.userId = userId;
    }

    /**
     * Gets the timestamp when this user was created.
     *
     * @return the creation timestamp
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Sets the creation timestamp.
     *
     * @param newCreatedAt the creation timestamp to set
     */
    public void setCreatedAt(final Instant newCreatedAt) {
        this.createdAt = newCreatedAt;
    }

    /**
     * Gets the timestamp of the user's last API access.
     *
     * @return the last access timestamp
     */
    public Instant getLastAccessedAt() {
        return lastAccessedAt;
    }

    /**
     * Sets the last access timestamp.
     *
     * @param newLastAccessedAt the last access timestamp to set
     */
    public void setLastAccessedAt(final Instant newLastAccessedAt) {
        this.lastAccessedAt = newLastAccessedAt;
    }

    /**
     * Updates the last accessed timestamp to the current time.
     */
    public void updateLastAccess() {
        this.lastAccessedAt = Instant.now();
    }
}
